Laboratorio_Cifrado/Controllers/CifradoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Text;
using Laboratorio_Cifrado.Utilities;


namespace Laboratorio_Cifrado.Controllers
{
    public class CifradoController : Controller
    {
        public static string directorioArchivos = System.Web.HttpContext.Current.Server.MapPath("~/Archivos/");
        public static string directorioUploads = System.Web.HttpContext.Current.Server.MapPath("~/Archivos/Uploads/");
        public static string directorioLlaves = System.Web.HttpContext.Current.Server.MapPath("~/Llaves/");

        public static string currentFile = "";
        public static string publicKey = directorioLlaves + "public.key";
        public static string privateKey = directorioLlaves + "private.key";

        public ActionResult GenerarLlaves()
        {
            CreateDirectories();
            return View();
        }
        [HttpPost]
        public ActionResult GenerarLlaves(string p, string q)
        {
            if (int.TryParse(p, out int NumeroP) && int.TryParse(q, out int NumeroQ))
            {
                if (NumerosPrimos.esNumeroPrimo(NumeroP) && NumerosPrimos.esNumeroPrimo(NumeroQ))
                {
                    if (NumeroP * NumeroQ >= 256) 
                    {
                        Llaves.GenerarLlaves(NumeroP, NumeroQ);
                        
                        return DownloadKeys();
                    }
                    else
                    {
                        ViewBag.Message = "P y Q deben ser numeros mayores";
                    }
                }
                else
                {
                    ViewBag.Message = "P y Q deben ser numeros primos";
                }
            }
            else
            {
                ViewBag.Message = "Entrada no valida";
            }

            return View();
        }

        public ActionResult RSA()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RSA(HttpPostedFileBase file, HttpPostedFileBase clave)
        {
            if (file != null && clave != null)
            {
                string pathArchivo = Path.Combine(directorioUploads, Path.GetFileName(file.FileName) ?? "");
                string pathClave = Path.Combine(directorioUploads, Path.GetFileName(clave.FileName) ?? "");

                UploadFile(pathArchivo, file);
                UploadFile(pathClave, clave);

                //leer texto de la archivo llave
                string[] keyText =  System.IO.File.ReadAllText(pathClave).Split(',');

                int.TryParse(keyText[0], out int power);
                int.TryParse(keyText[1], out int N);

                Utilities.RSA.Cifrar(pathArchivo, power, N);

                return RedirectToAction("Download");
            }
            else
            {
                ViewBag.Message = "Debe especificar el archivo";
            }

            return View();
        }

        public ActionResult Index()
        {
            CreateDirectories();
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, string password, string cifrado, string operacion)
        {
            //Validar datos de entrada
            
            if (file != null)
            {
                //Subir Archivo
                if (validarPassword(password, cifrado))
                {
                    string path = Path.Combine(directorioUploads, Path.GetFileName(file.FileName) ?? "");
                    UploadFile(path, file);


                    switch (operacion)
                    {
                        case "1": //Cifrar
                            switch (cifrado)
                            {
                                case "1": //Cesar

                                    Cesar.Cifrado(path, password);

                                    break;
                                case "2": //Zig Zag

                                    int corrimiento = Convert.ToInt32(password);
                                    ZigZag.Cifrado(path, corrimiento);

                                    break;
                                case "3": //Espiral

                                    int clave = Convert.ToInt32(password);
                                    Espiral.Cifrar(path, clave);

                                    break;

                                case "4": //SDES

                                    int passwordSDES = Convert.ToInt32(password);
                                    SDES CifradoSdes = new SDES();
                                    CifradoSdes.Cifrar(path, passwordSDES);

                                    break;
                            }
                            break;
                        case "2": //Descifrar
                            switch (cifrado)
                            {
                                case "1": //Cesar

                                    Cesar.Descifrar(path, password);

                                    break;
                                case "2": //Zig Zag

                                    int corrimiento = Convert.ToInt32(password);
                                    ZigZag.Descifrar(path, corrimiento);

                                    break;
                                case "3": //Espiral

                                    int clave = Convert.ToInt32(password);
                                    Espiral.Descifrar(path, clave);

                                    break;
                                case "4": //SDES

                                    int passwordSDES = Convert.ToInt32(password);
                                    SDES CifradoSdes = new SDES();
                                    CifradoSdes.Descifrar(path, passwordSDES);

                                    break;
                            }
                            break;
                    }

                    return RedirectToAction("Download");
                }
            }
            else
            {
                ViewBag.Message = "No ha especificado un archivo.";
            }

            return View();
        }

        public ActionResult Download()
        {
            return View();
        }

        private void CreateDirectories()
        {
            if (!Directory.Exists(directorioArchivos))
            {
                Directory.CreateDirectory(directorioArchivos);
            }
            if (!Directory.Exists(directorioUploads))
            {
                Directory.CreateDirectory(directorioUploads);
            }
            if (!Directory.Exists(directorioLlaves))
            {
                Directory.CreateDirectory(directorioLlaves);
            }
        }
        
        #region download
        public ActionResult DownloadFile()
        {
            string path = currentFile;

            if (!String.IsNullOrEmpty(path))
            {
                byte[] filedata = System.IO.File.ReadAllBytes(path);

                var cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = Path.GetFileName(path),
                    Inline = true,
                };

                currentFile = "";

                Response.AppendHeader("Content-Disposition", cd.ToString());
                return File(filedata, "application/force-download");
            }
            else
            {
                ViewBag.Message = "No existe el archivo";
                return RedirectToAction("Download");
            }
        }

        private ActionResult DownloadKeys()
        {
            using (var memoryStream = new MemoryStream())
            {
                using (var archive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                {
                    var file1 = archive.CreateEntry("public.key");
                    using (var streamWriter = new StreamWriter(file1.Open()))
                    {
                        streamWriter.Write(System.IO.File.ReadAllText(publicKey));
                    }

                    var file2 = archive.CreateEntry("private.key");
                    using (var streamWriter = new StreamWriter(file2.Open()))
                    {
                        streamWriter.Write(System.IO.File.ReadAllText(privateKey));
                    }
                }

                return File(memoryStream.ToArray(), "application/zip", "Keys.zip");
            }
        }
        #endregion

        #region upload
        public void UploadFile(string path, HttpPostedFileBase file)
        {
            //Subir archivos al servidor
            
            if (file != null && file.ContentLength > 0)
                try
                {
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    file.SaveAs(path);
                    ViewBag.Message = "Carga Exitosa";

                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message;
                }
            else
            {
                ViewBag.Message = "No ha especificado un archivo.";
            }
        }
        #endregion

        #region Contraseña

        private bool validarPassword(string password, string cifrado)
        {
            bool resultado = false;

            int i;
            switch (cifrado)
            {
                case "1": //Cesar

                    if (password.All(char.IsLetter))
                    {
                        if (password.Distinct().Count() == password.Length)
                        {
                            resultado = true;
                        }
                        else
                        {

Laboratorio_Cifrado/Views/Cifrado/Download.cshtml
@{
    ViewBag.Title = "Download";
}

<div class="jumbotron">
    <h3>Laboratorio No. 2</h3>
</div>

Presione el siguiente botón para descargar su archivo: <br><br>
<div>
    <input type = "button" value = "Download"
           onclick = "location.href = '@Url.Action("DownloadFile", "Cifrado")'" %>
</div>

@ViewBag.Message

Laboratorio_Cifrado/Views/Cifrado/GenerarLlaves.cshtml
@{
    ViewBag.Title = "RSA";
}


<div class="jumbotron">
    <h3>Escriba dos numeros primos para generar llaves RSA</h3>
</div>

@using (Html.BeginForm("GenerarLlaves", "Cifrado", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <label for="p">Ingrese P:</label>
    <input type="text" name="p" id="p" /><br>

    <label for="q">Ingrese Q:</label>
    <input type="text" name="q" id="q" /> <br>
    
    <br>
    <input type="submit" value="Aceptar" />

    <br><br>

    <label style="color: red">@ViewBag.Message</label>
}

Laboratorio_Cifrado/Views/Cifrado/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="jumbotron">
    <h3>Subir archivo a Cifrar</h3>
</div>

@using (Html.BeginForm("Index", "Cifrado", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <label for="file">Subir archivo:</label>
    <input type="file" name="file" id="file" /><br>

    <label for="password">Ingrese Contraseña:</label>
    <input type="password" name="password" id="password" /> <br>

    <label for="cifrado">Ingrese Tipo de Cifrado:</label>
    <select id="cifrado" name="cifrado">
        <option value="4">SDES</option>
        <option value="1">César</option>
        <option value="2">Zig Zag</option>
        <option value="3">Espiral</option>
    </select>
    <br>

    <label for="operacion">Ingrese Operacion a Realizar:</label>
    <select id="operacion" name="Operacion">
        <option value="1">Cifrar</option>
        <option value="2">Descifrar</option>
    </select>
    <br>
    
    <br>
    <input type="submit" value="Aceptar" />

    <br><br>

    <label style="color: red">@ViewBag.Message</label>
}

Laboratorio_Cifrado/Views/Cifrado/RSA.cshtml
@{
    ViewBag.Title = "RSA";
}

<h2>RSA</h2>

<div class="jumbotron">
    <h3>Subir archivo a Cifrar</h3>
</div>

@using (Html.BeginForm("RSA", "Cifrado", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <label for="file">Subir archivo a cifrar/descifrar:</label>
    <input type="file" name="file" id="file" /><br>

    <label for="clave">Subir archivo de llave:</label>
    <input type="file" name="clave" id="clave" /><br>

    <br>
    <input type="submit" value="Aceptar" />

    <br><br>

    <label style="color: red">@ViewBag.Message</label>
}